# Generated by Django 5.2.5 on 2025-11-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tractor', 'Tractor'), ('sprayer', 'Sprayer'), ('rotavator', 'Rotavator'), ('harvester', 'Harvester'), ('irrigation', 'Irrigation'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('rent_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rent_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
