# Generated by Django 5.2.5 on 2025-11-25 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
        ('equipment', '0003_alter_equipment_options_equipment_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration_type',
            field=models.CharField(choices=[('days', 'Days'), ('hours', 'Hours')], default='days', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='equipment.equipment'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings_booking',
        ),
    ]
