# Generated by Django 5.2.5 on 2025-11-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_options_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash on Delivery')], default='cash', max_length=20),
        ),
    ]
